### ISSUE TITLE
Section 1.2 - introduction

### ISSUE THREAD

**Issue by shantenujha** [radical-cybertools/radical.ensemblemd#100]
To discuss

e.g., 
"Decoupling the execution from the expression of the pattern allows the execution plugins to analyze an application’s control- and dataflow, combine the results with existing information about the execution resource and execute according to the derived strategy. "

execution strategy is not defined. 

I refined/removed many other things in introduction.

**Comment by vivek-bala** [comment]
"execution strategy", "execution plugin" definition/discuss.
