### ISSUE TITLE
transpose order?

### ISSUE THREAD

**Issue by shantenujha** [radical-cybertools/radical.ensemblemd#101]
I'm looking at the order in which Execution Context and Execution pattern are discussed in:

http://radicalensemblemd.readthedocs.org/en/docs_vivek/user_guide/getstarted.html

Looking at the code, at http://radicalensemblemd.readthedocs.org/en/docs_vivek/_downloads/get_started.py

shouldn't we discuss Execution Pattern before Execution Context?

**Comment by vivek-bala** [comment]
This needs discussion. In terms of the control flow, it is first the execution context that is created and then execution pattern.
