### ISSUE TITLE
0.2-119-g71a02c6 is not 0.3!

### ISSUE THREAD

**Issue by shantenujha** [radical-cybertools/radical.ensemblemd#103]
I followed the instructions to install per:

http://radicalensemblemd.readthedocs.org/en/docs_vivek/installation.html

After "successful installation" I get:

(EnMDToolkit)RandomDisorder:cecam shantenu$ ensemblemd-version
0.2-119-g71a02c6

Per document I should get

0.3

0.2-119-g71a02c6 is not 0.3 (the last I checked :) )

**Comment by vivek-bala** [comment]
Add a static version number. Actual method will change once tag is created.
