### ISSUE TITLE
downloaded file does not work!

### ISSUE THREAD

**Issue by shantenujha** [radical-cybertools/radical.ensemblemd#104]
I downloaded get_started.py

from

http://radicalensemblemd.readthedocs.org/en/docs_vivek/_downloads/get_started.py

as per

http://radicalensemblemd.readthedocs.org/en/docs_vivek/user_guide/getstarted.html

But I get:

(EnMDToolkit)RandomDisorder:cecam shantenu$ python get_started.py 
  File "get_started.py", line 35
    except EnsemblemdError, er:
         ^
SyntaxError: invalid syntax

**Comment by vivek-bala** [comment]
fixed in devel
