### ISSUE TITLE
"Do you want Python accept incoming network connections"?

### ISSUE THREAD

**Issue by shantenujha** [radical-cybertools/radical.ensemblemd#107]
When running examples from 0.3RC 

Do you want the application “python” to accept incoming network connections?

Also, get this weird message about python... "Clicking Deny may limit the application’s behavior. This setting can be changed in the Firewall pane of Security & Privacy preferences."

DENY or ALLOW

**Comment by andre-merzky** [comment]
This is a setting of you local  firewall I think - I doubt there is much we can do about it from an RP perspective...

**Comment by marksantcroos** [comment]
I believe this only happens when you run python inside the CU. IS this the case here? I got around that by self-signing the python inside the VE. Which is not something we want to document. We can document "click allow" though.

**Comment by vivek-bala** [comment]
Should this be documented (incase we expect that some attendees might possibly run into this ) ?

**Comment by vivek-bala** [comment]
> I believe this only happens when you run python inside the CU. IS this the case here?

In one of the usecases, yes.

**Comment by marksantcroos** [comment]
https://github.com/radical-cybertools/radical.pilot/blob/release/v0.37/docs/source/faq.rst#avoid-the-pop-up-do-you-want-the-application-python-to-accept-incoming-network-connections-on-mac-osx

**Comment by andre-merzky** [comment]
Thanks Mark!
