### ISSUE TITLE
Pip installation failing

### ISSUE THREAD

**Issue by Nikhil-Shenoy** [radical-cybertools/radical.ensemblemd#108]
For the Enmd Release Testing, I cloned the Enmd repository and am trying to install it with the command "pip install --upgrade ."

Whenever I do this, I get the following error:

```
Command /home/shenoy/envs/ve/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-RDSaCz/radical.utils/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-9eTGXx-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/shenoy/envs/ve/include/site/python2.7 failed with error code 1 in /tmp/pip-build-RDSaCz/radical.utils
Storing debug log for failure in /home/shenoy/.pip/pip.log
```

I get this error no matter which repository I clone, be it Radical Utils, Radical Pilot, or EnsembleMD. 

Is there a better way for me to install the packages?

**Comment by andre-merzky** [comment]
Please try again with   pip 1.4.1.  Thanks!

**Comment by marksantcroos** [comment]
i.e. `pip install --upgrade pip==1.4.1`

**Comment by Nikhil-Shenoy** [comment]
Sorry for the late reply. It worked!
