### ISSUE TITLE
levenstein example?

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.ensemblemd#114]
The CECAM excercise asks to pick three from the examples dir.  The levenstein example fails due to missing parameters, and I could not find out what input files it wants  - should it be moved out of here for the time being?  Or print some help message?

**Comment by andre-merzky** [comment]
same for matrix_calculator.py

**Comment by vivek-bala** [comment]
OK that needs to be documented. Those two are input files to enmd scripts.

**Comment by vivek-bala** [comment]
documented in the cecam wiki.
