### ISSUE TITLE
Database connection error

### ISSUE THREAD

**Issue by suvigya91** [radical-cybertools/radical.ensemblemd#126]
Hi,
I installed EnsembleMD, ran get_started.py and got following error

================================================================================
 EnsembleMD (0.3.14)                                                            
================================================================================

Starting Allocation2016-01-14 18:37:51,926: radical.pilot       : MainProcess                     : MainThread     : ERROR   : session create failed
Traceback (most recent call last):
  File "/home/suvigya/myenv/local/lib/python2.7/site-packages/radical/pilot/session.py", line 141, in __init__
    dburl = self._dburl)
  File "/home/suvigya/myenv/local/lib/python2.7/site-packages/radical/pilot/db/database.py", line 56, in __init__
    mongo, db, _, _, _ = ru.mongodb_connect(str(dburl))
  File "/home/suvigya/myenv/local/lib/python2.7/site-packages/radical/utils/misc.py", line 88, in mongodb_connect
    mongo = pymongo.MongoClient (host=host, port=port)
  File "/home/suvigya/myenv/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 377, in __init__
    raise ConnectionFailure(str(e))
ConnectionFailure: timed out
Traceback (most recent call last):
  File "get_started.py", line 55, in <module>
    cluster.allocate()
  File "/home/suvigya/myenv/local/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 150, in allocate
    self._session = radical.pilot.Session(database_url=db_url)
  File "/home/suvigya/myenv/local/lib/python2.7/site-packages/radical/pilot/session.py", line 150, in __init__
    % (self._dburl, ex))  
radical.pilot.exceptions.PilotException: Couldn't create new session (database URL 'mongodb://ec2-54-221-194-147.compute-1.amazonaws.com:24242/myexps' incorrect?): timed out

I am not sure if I am running it correctly.
Thanks!

**Comment by marksantcroos** [comment]
That probably means ensemblemd has its own mechanism to set the db as your environment variable is not honoured. Can you find it in one of the configs?

**Comment by suvigya91** [comment]
Hi Mark,
I could not find the db in the config. Where exactly should I look for it?
Thanks!

**Comment by marksantcroos** [comment]
Its actually in your get_started.py script: https://github.com/radical-cybertools/radical.ensemblemd/blob/master/doc/user_guide/scripts/get_started.py#L49

I don't know enough about ensemblemd to say why it is like that.

**Comment by suvigya91** [comment]
Yes, I exactly have the same db url in my get_started.py script. But how to get rid of the error I am getting?

**Comment by marksantcroos** [comment]
What do you mean with the same?
You should specify a working database there. Either one on localhost or somewhere else.

**Comment by suvigya91** [comment]
Hi Mark,
I did not understand previously but got it now. It works. 
Thanks

**Comment by vivek-bala** [comment]
First priority is for the RADICAL_PILOT_DBURL environment variable, then the database url specified in the script. So if you have both, the dburl specified via the environment variable will get picked up.

**Comment by vivek-bala** [comment]
Oops. Sorry, it is the other way around. First priority is for the dburl specified in the script. If that does not exist, the environment variable is picked up.
