### ISSUE TITLE
Mapping of Profiler probes to State Model

### ISSUE THREAD

**Issue by Nikhil-Shenoy** [radical-cybertools/radical.ensemblemd#129]
I was wondering whether the states probed in the EnMD profiler correspond directly to the state model. For example, the profiler generates a file with these headings:

``Scheduling, StagingInput, AgentStagingInputPending, AgentStagingInput, AllocatingPending, Allocating, ExecutingPending, Executing, AgentStagingOutputPending, AgentStagingOutput, PendingOutputStaging, StagingOutput, Done``

Which state model do these states correspond to, if any?

**Comment by vivek-bala** [comment]
I think this is https://docs.google.com/drawings/d/1q5ehxIVdln5tXEn34mJyWAmxBk_DqZ5wwkl3En-t5jo/edit.

* "Agent_scheduling" is called "allocating" now.
* PendingStagingInput/StagingInputPending and PendingScheduling/SchedulingPending states weren't logged. so they are now available in the enmd profiler.
