### ISSUE TITLE
Stampede allocation in config file currently has -4 SUs

### ISSUE THREAD

**Issue by antonst** [radical-cybertools/radical.ensemblemd#143]

**Comment by vivek-bala** [comment]
ahh.. its using the wrong project. I thought I changed it in all the files. which file is this ?

**Comment by antonst** [comment]
config in examples

**Comment by vivek-bala** [comment]
Thanks Antons. Thought I had it updated, but I guess not. I am making a new branch for all the non-documentation related issues pointed out by you and George. I'll update the testing sheet to the same.
