### ISSUE TITLE
6. Running a Gromacs/LSDMap Workload

### ISSUE THREAD

**Issue by georgeha** [radical-cybertools/radical.ensemblemd#145]
In the documentation you state in Step two to : cd grlsd-on-stampede, whereas in the tarball the folder name is gromacs-lsdmap

**Comment by vivek-bala** [comment]
Thanks george. I'll keep note of that and fix it with the final merge.

**Comment by vivek-bala** [comment]
This is fixed. The tarball for the workshop is linked with the wiki documentation.
