### ISSUE TITLE
Ensemble/Conda Integration

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.ensemblemd#173]
Instead of using virtualenv, how can I use conda with ensemble???

**Comment by andre-merzky** [comment]
Iannis is the resident expert on (ana)conda related things, and may be able to set you up.  On the RP layer, you will basically have to use specific resource labels.  I am not sure what (if anything) is specifically required on the EnTK layer..

**Comment by iparask** [comment]
The ```setup.py``` file should be written the same way as RP's. Then, EnTK can be installed in a conda VE. The label you are speaking about is for when the target resource has Anaconda

**Comment by vivek-bala** [comment]
Thanks Giannis !

**Comment by iparask** [comment]
Apparently, it is okay as it is. I am closing the ticket.
