### ISSUE TITLE
EnsembleMD Profiling Variable

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.ensemblemd#19]
Hi all,

the variable in the code is written as RADICAL_ENDM_PROFILING. Shouldn't it change to RADICAL_ENMD_PROFILING? Also I realized that when you do RADICAL_ENMD_PROFILING=0 it still creates the CSV file.

Maybe a change in the check like " !='0' " can resolve this issue?

**Comment by oleweidner** [comment]
Good catch. Fixed in master & devel. Please try.
