### ISSUE TITLE
counting of steps, etc.

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.ensemblemd#25]
I guess the reason to start counting with 1 is to be "user-friendly". But given that the users are writing this in python, isn't that counter-intuitive?

**Comment by oleweidner** [comment]
So you are technically saying that "python" and "user friendly" are mutually exclusive :-) 

I think this is really just a matter of convention and proper documentation. I find it always a bit more intuitive to talk about the 'first' iteration of a pattern and the 'first' step of a pipeline. "zeroth" step or iteration doesn't sound very intuitive to me.

**Comment by oleweidner** [comment]
stick to '1'.
