### ISSUE TITLE
unclear error on missing project/allocation

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.ensemblemd#26]
When not specifying a project or allocation, we get an error about missing "project" field from RP.
Adding this doesn't help, reading the documentation turned out that this field is called "allocation".

Besides the (unwarranted?) inconsistency that it creates, its not clear from the error message.

**Comment by oleweidner** [comment]
rename to 'project'.

**Comment by vivek-bala** [comment]
changed to project in all examples/usecases. 381262c41fec92d668acac471ce7ea2542f08835
