### ISSUE TITLE
AllPairs example

### ISSUE THREAD

**Issue by AntonsT** [radical-cybertools/radical.ensemblemd#29]
It would be beneficial if documentation would mention which kernel(s) are used in this generic example as well as what are the input files and what are the expected output files. How do I interpret the output files? For example comparison-1-2.log contains only one char: '1'. What does that mean? Is this expected output?

line 82:
Do not know yet what should be printed...
This comment should be removed.

**Comment by iparask** [comment]
In the ``element_initialization`` step, the necessary files for the all pair are created. This step uses the ``misc.mkfile`` kernel to create random ASCII files. Those files represent the elements of the set upon which the ``AllPairs`` pattern will be executed. After the creation an ``element_comparison`` will be executed for each unique pair of files (elements of the set). The ``element_comparison`` here executes the ``misc.diff`` kernel which returns the number of different lines between the files. In the end the result files are downloaded to the folder from which the script was run.

I will add it in the comments

**Comment by AntonsT** [comment]
OK, thanks. I also have another suggestion. Maybe this pattern should be named simply AllPairs insted of AllPairsPattern? This way pattern name would be consistent with other patterns.

Thanks,
Antons

**Comment by AntonsT** [comment]
Also in execution profile could you please replace p1 and p2 with something more meaningful?

Thanks,
Antons

**Comment by AntonsT** [comment]
grammatical mistake:
the necessary files for the all "pair" are created

**Comment by AntonsT** [comment]
comment (line 52):
>I think it download the output files from the cluster to the machine
>that run this script. Need to learn more here.
needs to be removed

**Comment by AntonsT** [comment]
I don't understand sentence:
>Once the script has finished running, you should see <Need to implement it completely to know the >output files. Probably one file for everything?>the in the same directory you launched the script in.

**Comment by AntonsT** [comment]
grammatical mistake:
>Completed Succefully!

**Comment by iparask** [comment]
Thank you Antons!
