### ISSUE TITLE
Memory Consuption

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.ensemblemd#33]
Dear all,

during testing the simulation analysis example for 4 iterations, 512 simulation instances and 512 analysis instances on Stampede, the script consumed over 5GB of RAM on my machine, which has 10GB in total, while waiting for the execution of the analysis tasks in iteration 2.

Is this expected or not? Also, is this because of EnsembleMD or is it something observed also in Radical Pilot?

Mark, have you observed a similar behavior?

**Comment by andre-merzky** [comment]
I am regularly running large runs from a smallish VM, as does Matteo, w/o apparent memory troubles, so I don't think thats on RP level.  I'll keep an eye on it though...

**Comment by marksantcroos** [comment]
I still have to run those large ones. Will keep an extra eye on memory consumption.

**Comment by oleweidner** [comment]
Will try that as well...

**Comment by oleweidner** [comment]
So I managed to reproduce this over the weekend. Furthermore, I'm pretty sure that this is *not* a problem with RADICAL-Pilot. I ran a few RP-only tests and couldn't observe any excessive memory consumption. 

Why this is happening with the Simulation-Analysis pattern, I cannot quite say yet. I'm in the process of debugging it....

Stay tuned.

**Comment by oleweidner** [comment]
@iparask: are you sure you are reporting real memory and not virtual memory size? When I run the example repeatedly, I never manage to exceed 1,5 GB total real memory.

However, I did notice something else which probably explains the 'hanging' you experience after the analysis step: internally, EnsembleMD uses a lot of environment variables to reference other CU's working directories, etc. These are all added as `ComputeUnitDescription.environment`, which leads to rather large CU Descriptions: for 512 CUs in the second step (env vars increase with more iterations), the total size of CUDs that are submitted to MongoDB is 70 MB. Depending on your connectivity (esp. latency), this can take quite some time. 

I am not sure if I can come up with a quick fix for this without ripping the entire execution plug-in apart, but I will try. 

In the mean-time, can you please increase the pilot runtime from 30 minutes to 120 minutes and try to run the 512-instance case again, please? Keep and eye on the real memory consumption of the process and let me know what you see. 

Thanks!

**Comment by andre-merzky** [comment]
`cud.environment` should be a dict -- how is one entry increasing memory
consumption when being se repeatedly?

On Mon, Jan 26, 2015 at 5:24 PM, Ole Weidner <notifications@github.com>
wrote:

> @iparask <https://github.com/iparask>: are you sure you are reporting
> real memory and not virtual memory size? When I run the example repeatedly,
> I never manage to exceed 1,5 GB total real memory.
>
> However, I did notice something else which probably explains the 'hanging'
> you experience after the analysis step: internally, EnsembleMD uses a lot
> of environment variables to reference other CU's working directories, etc.
> These are all added as ComputeUnitDescription.environment, which leads to
> rather large CU Descriptions: for 512 CUs in the second step (env vars
> increase with more iterations), the total size of CUDs that are submitted
> to MongoDB is 70 MB. Depending on your connectivity (esp. latency), this
> can take quite some time.
>
> I am not sure if I can come up with a quick fix for this without ripping
> the entire execution plug-in apart, but I will try.
>
> In the mean-time, can you please increase the pilot runtime from 30
> minutes to 120 minutes and try to run the 512-instance case again, please?
> Keep and eye on the real memory consumption of the process and let me know
> what you see.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radical-cybertools/radical.ensemblemd/issues/33#issuecomment-71488132>
> .
>



-- 
'So much time, so little to do...' (Garfield)

**Comment by oleweidner** [comment]
For each iteration the number of environment variables increases. In the second step it's 512 per CU. In the third step it's 1024 per CU and so on. Multiply this by something like 100 bytes per environment variable and 1024 tasks and you end up with ~ 60 MB worth of CU description. 

While it was really convenient to do everything via environment variables (it allowed use to resolve all CU dependencies on the remote end), I guess this show that the approach is not scalable. Solution will be to resolve CU dependencies on the client-side we don't have to send the "dependency dictionary" (all those env variables) to MongoDB anymore.

**Comment by andre-merzky** [comment]
Wow...

I could not find that in the code though -- can you point me to where this is implemented?  Thanks!

**Comment by andre-merzky** [comment]
Never mind, found it now -- its not in the `cud.environment`, but in `cud.pre_exec` :P  Anyway, I totally agree that those things should be evaluated on the ensemblemd end, not in the CU runtime environment (which is too late for staging anyway, amongst other things...).

**Comment by oleweidner** [comment]
Hi @iparask, the rampant memory consumption is a thin of the past in the latest release candidate (RC-6). I have it down to a total of 300 MB for the entire "512,512,4" simulation analysis example. This is consistent with my radical-pilot only tests. 

Please give it a try again and let me know how it goes!

**Comment by iparask** [comment]
Okay. I am running it now. If I have something I will tell you
