### ISSUE TITLE
Designer's guide

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.ensemblemd#36]
I think that a designer's guide and a paragraph or two describing the philosophy of Ensemble MD from a designer perspective and how one can integrate and develop a new feature would be extremely helpful and informative.

**Comment by oleweidner** [comment]
Ok, so I have been working on an 'architecture in a nutshell' guide: https://docs.google.com/document/d/1LaJZHrfzJlXi1kuaoSucINJbu-TUtlvMDbV0kz6CLk8/edit#. Please let me know if this is the level of detail you were envisioning and I will extend to document to include the remaining components of EnMD.
