### ISSUE TITLE
extasy_coco_amber usecase documentation

### ISSUE THREAD

**Issue by AntonsT** [radical-cybertools/radical.ensemblemd#37]
'numCUs' is not present in code, but covered in documentation.
What is num_sims? not explained and name is not descriptive.
In pre_loop, why RP shared data transfer routines are not used?
No comments for post_loop.
If I launch this script what it actually does? e.g. how many iterations will be performed and how many instances of MD package will be launched?
Why in usecases/extasy_coco_amber (master branch) is present unimplemented DYNAMIC simulation-analysis example?
If I use RADICAL_ENMD_PROFILING=1:
 - Total simulation time is not provided
 - Time for analysis step is not provided
 - Time for simulation step is not provided

**Comment by AntonsT** [comment]
Also, when I cd into that directory there are seven files, three of which are python files. Which of these should I launch? Maybe input files should be put into separate directory?

**Comment by AntonsT** [comment]
How do I change the number of iterations? What is iteration?

**Comment by AntonsT** [comment]
How to I know is simulation was successfull or not?

**Comment by AntonsT** [comment]
Why on 16 cores we are launching 8 simulation_instances per iteration?

**Comment by vivek-bala** [comment]
Updated in devel. Dynamic simulation-analysis is to be in the later releases. Created a separate ticket for the profiling points #47.
