### ISSUE TITLE
extasy_gromacs_lsdmap documentation

### ISSUE THREAD

**Issue by AntonsT** [radical-cybertools/radical.ensemblemd#38]
There are 12 files in usecases/extasy_gromacs_lsdmap directory. Maybe these should be organised somehow? 
pre_analyze.py - no comments at all
post_analyze.py - no comments at all
spliter.py - no comments at all
select.py - needs more comments
run.py - needs more comments
What are the relationships between these files? If there are just two stages, e.g. simulation analysis why there are seven python files? merge them?

01_static_gromacs_lsdmap_loop.py:
line 57: # TODO Vivek: add description. ?
pre_loop() - why not RP shared data routines?
So if 'numCUs' is the number of simulation instances per iteration and 'nsave' is the iteration at which backup needs to be created on the local machine how can I know how many iterations this script actually performs? 
How can I change the number of iterations?
Why on 16 cores we are launching 8 CU's per iteration?

**Comment by AntonsT** [comment]
line188  # We set the 'instances' of the simulation step to 16. but this is hardcoded as num_CUs = 8

**Comment by AntonsT** [comment]
If I use RADICAL_ENMD_PROFILING=1:

    Total simulation time is not provided
    Time for analysis step is not provided
    Time for simulation step is not provided

**Comment by vivek-bala** [comment]
description of files and individual parameters has been added in devel. Profiling has been addressed by Ole in the documentation.
