### ISSUE TITLE
usecases/haussdorff: documentation

### ISSUE THREAD

**Issue by AntonsT** [radical-cybertools/radical.ensemblemd#41]
How do I run this script locally, remotely?
What it does?

**Comment by AntonsT** [comment]
class MyHausdorff should not be in this file ---> kernel_plugins
class MyQPC should not be in this file ---> kernel_plugins

**Comment by AntonsT** [comment]
line 177: "HausdorffAP implements the all pairs pattern described above" Where?
line 253: "Everything is downloaded!" what is Everything? Does it indicate success? 
How do I vary the number of pairs?

**Comment by iparask** [comment]
Completed
