### ISSUE TITLE
Improve error handling so that cu.uid of a failed replica is displayed when error is raised

### ISSUE THREAD

**Issue by AntonsT** [radical-cybertools/radical.ensemblemd#44]
Now this is something like:
File "replica_exchange_mode_1.py", line 294, in get_swap_matrix
swap_matrix[i][r.id] = float(matrix_columns[r.id][i])
ValueError: could not convert string to float: None

This is because matrix calculator returned None, e.g. output files are not found, e.g. CU failed.

**Comment by oleweidner** [comment]
same cause as #54
