### ISSUE TITLE
simulation analysis loop profiling

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.ensemblemd#47]
Total simulation time is not provided
    Time for analysis step is not provided
    Time for simulation step is not provided

**Comment by oleweidner** [comment]
This is best be done by implementing the execution_profile property: http://radicalensemblemd.readthedocs.org/en/devel/dev_profiling.html#runtime-profile-via-api. See the Pipeline and Simulation-Analysis pattern for a working implementation.

**Comment by vivek-bala** [comment]
Ah ok. Was about to start with this. Thanks Ole. Shouldn't it be 'sim_2_ *exec*_ time' as opposed to 'sim_2_ *end*_ time' in http://radicalensemblemd.readthedocs.org/en/devel/dev_profiling.html#runtime-profile-via-api ?

**Comment by oleweidner** [comment]
No, it's actually the end time of the step, assuming that start time of the pattern is 0.0. I.e., 34 means that the step ended 34 seconds after the pattern has started execution.

**Comment by vivek-bala** [comment]
Ok, then execution time as well as experiment progression with timestamps will be known. Makes sense.
