### ISSUE TITLE
Extasy Coco Amber Use Case Fails on Stampede

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.ensemblemd#50]
When I run the Extasy Coco Amber Use Case Fails on Stampede. The log file is here:

https://gist.github.com/iparask/00b893c19cca5f19eab8

**Comment by AntonsT** [comment]
Whoops

**Comment by iparask** [comment]
Uploaded again!

https://gist.github.com/iparask/5e75c66170fe257203ac

**Comment by vivek-bala** [comment]
This is pretty old (feb 18), please try again whenever possible.

**Comment by vivek-bala** [comment]
This was because of permissions. Resolved.
