### ISSUE TITLE
Stray '/' in log

### ISSUE THREAD

**Issue by oleweidner** [radical-cybertools/radical.ensemblemd#51]
```Waiting for analysis tasks in iteration 1/kernel 1 to complete```

**Comment by vivek-bala** [comment]
That was intended. Analysis in gromacs-lsdmap is split into three kernels. Hence, iteration n/kernel 1. Alternate ideas ?

**Comment by oleweidner** [comment]
Ah, ok. Maybe some more information, like `1/kernel 1 (kernelname)` to complete
