### ISSUE TITLE
Add FAQ section

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.ensemblemd#56]
how to add and use user-defined kernels that are not supported in ensemblemd?
what is the users effort in setting up a SA Loop ?

**Comment by oleweidner** [comment]
There's now a FAQ section at: https://radicalensemblemd.readthedocs.org/en/master/faq.html

New entries are added to this file: https://github.com/radical-cybertools/radical.ensemblemd/blob/master/doc/faq.rst
