### ISSUE TITLE
kernel 'type' parameter for single/multiple instances of the kernel

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.ensemblemd#58]
It would be useful to be able to classify kernels as single/multi since there can be multiple kernels within a stage/step. In the case of the analysis stage in gromacs-lsdmap for example, the analysis stage has 3 kernels. 

In a (future) case, where multiple analysis instances (say N) are to be in the usecases, kernel 1: pre_lsdmap needs to execute only once **every N instances**, kernel 2: lsdmap executes once **every instance** (hence N times) and kernel 3: post_lsdmap executes once **every instance** (N times).
In such a case, it would be helpful if we can define kernel 1 as single and kernel 2 & 3 as multiple.

**Comment by marksantcroos** [comment]
Isn't this outside of the kernel?

**Comment by oleweidner** [comment]
Vivek will try to implement.

**Comment by vivek-bala** [comment]
added parameter to specify kernel instance type. defaults to single. 7eca09e38f98a99d5e30bb9ba37282bbea1c8a4f. Needs to be specified only if using both types ('single'/'multiple').
