### ISSUE TITLE
Order of timing details

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.ensemblemd#60]
The order of timings that gets printed out seems a bit difficult to follow :- 
```
{'name': 'simulation_step_1', 'timings': {'units_stageout_first_started': {'abs': None, 'rel': None}, 'start_time': {'abs': datetime.datetime(2015, 3, 10, 11, 39, 47, 103482), 'rel': datetime.timedelta(0, 0, 619)}, 'units_exec_last_finished': {'abs': datetime.datetime(2015, 3, 10, 15, 40, 2, 69000), 'rel': datetime.timedelta(0, 0, 717000)}, 'units_stagein_first_started': {'abs': None, 'rel': None}, 'end_time': {'abs': datetime.datetime(2015, 3, 10, 11, 40, 2, 213710), 'rel': datetime.timedelta(0, 15, 110847)}, 'units_stageout_last_finished': {'abs': None, 'rel': None}, 'units_exec_first_started': {'abs': datetime.datetime(2015, 3, 10, 15, 40, 1, 352000), 'rel': datetime.timedelta(0)}, 'units_stagein_last_finished': {'abs': None, 'rel': None}}}
```

The order is different from what is shown in 6.2.1.

**Comment by vivek-bala** [comment]
Also,

1) "simulation_step_iter_1" would be easier to understand than "simulation_step_1".
2) I think the "units" in "units_stageout_*" can be avoided too or replaced with "step" or "simulation/analysis". This would make sense to users (non-RP users, who might not be familiar with "units") who would like to do some scaling tests (with their specific kernels for e.g.).

**Comment by oleweidner** [comment]
I Vivek - I have fixed the naming (among some other improvements). Please check http://radicalensemblemd.readthedocs.org/en/latest/dev_profiling.html. 

Hope this makes more sense now. Please close the ticket if you think your comments have been addressed.

**Comment by vivek-bala** [comment]
Yes, it does.
