### ISSUE TITLE
User method to set the MongoDB url to be used

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.ensemblemd#61]
I think there should be a method that the user can use to set the mongodb url to be used. Currently, one has to set the RADICAL_PILOT_DBURL env variable.

**Comment by oleweidner** [comment]
Good point. 

Can you coordinate with Antons and Giannis, implement and document this? 

I think I would be in favor of adding an optional parameter to the ClusterEnvironment. If it's not set, then `RADICAL_PILOT_DBURL` is used. If that's not set either, an exception is thrown.

**Comment by vivek-bala** [comment]
Just to make sure.. we require an additional function to set the DB Url as opposed to another parameter in the SingleClusterEnvironment class (?).

**Comment by oleweidner** [comment]
I think an additional (optional) parameter would be better.

**Comment by vivek-bala** [comment]
added 'database_url' parameter in single cluster class: https://github.com/radical-cybertools/radical.ensemblemd/blob/devel/src/radical/ensemblemd/single_cluster_environment.py#L46. If not specified, defaults to environment variable RADICAL_PILOT_DBURL.
