### ISSUE TITLE
simulation-analysis profiling : data_stagein field empty in the dataframe

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.ensemblemd#63]
I am using the devel branch for profiling. I have data being staged in during the simulation stage (https://github.com/radical-cybertools/radical.ensemblemd/blob/master/usecases/extasy_gromacs_lsdmap/01_static_gromacs_lsdmap_loop.py#L171-L173), but the data_stagein field remains empty in the dataframe : https://gist.github.com/vivek-bala/0a57e898e05e72f454c1.

Same holds for the data_stagein for the Analysis stage as well.

**Comment by andre-merzky** [comment]
what pilot branch are you using?

**Comment by vivek-bala** [comment]
I believe this is the RP on pypi. (https://github.com/radical-cybertools/radical.ensemblemd/blob/devel/setup.py#L127)

**Comment by oleweidner** [comment]
Are your using "link_input_data" as your link above suggests? 'Linking' is not recorded as data staging.

**Comment by vivek-bala** [comment]
Hmmm .. Is it the same for 'copy_input_data' as well ? So "data_stagein" would mean transfer to the remote host and not the "staging" into the CUs in any of the simulation/analysis steps ?

**Comment by oleweidner** [comment]
Transfer that crosses host-boundaries and that are using RP's data staging are recorded. Linking and copying on the same host, i.e., between steps are not. 

Maybe that's something that can be improved in the future if the new RP staging directives are implemented throughout EnMD.

**Comment by andre-merzky** [comment]
> Transfer that crosses host-boundaries and that are using RP's data staging are recorded. Linking and copying on the same host, i.e., between steps are not.

In the devel branch, those actions are in enacted in different components, and thus have different states, and thus get separate entries in the state history, so they will be easy to dig out again.  If it is very urgent, we can do some kind of fixing in master, but devel is what represents the clean approach to that specific problem.

**Comment by vivek-bala** [comment]
This is resolved in the devel profiling.
