### ISSUE TITLE
Kernel: copy_output_data() is not implemented

### ISSUE THREAD

**Issue by AntonsT** [radical-cybertools/radical.ensemblemd#65]

**Comment by oleweidner** [comment]
This should be implemented on API level now. Whatever is passed as Kernel.copy_output_data should now be accessible in the execution plug-in. Let me know if this works. 

The 'devel' branch documentation reflects the latest changes: http://radicalensemblemd.readthedocs.org/en/devel/library.html#radical.ensemblemd.Kernel.copy_output_data

**Comment by AntonsT** [comment]
Yes, this does work now.
