### ISSUE TITLE
Return of log files after running allpairs_example.py on Stampede

### ISSUE THREAD

**Issue by Nikhil-Shenoy** [radical-cybertools/radical.ensemblemd#66]
I have run a slight modification of the allpairs_example.py on Stampede, but for some reason the log files do not get downloaded once the job finishes even though the script terminates without errors. When I run the script locally, everything works fine and the log files exist in the directory where I ran the file. I've looked both on my machine and on Stampede to find those files, but I have had no luck. Why would the log files not get downloaded back to my local machine from Stampede once the job finishes?

**Comment by iparask** [comment]
It should download the result file as soon as a task is completed. Can you upload the debug log file.

Thank you.
