### ISSUE TITLE
Using RP-devel stack: Resource error: Pilot launching failed!

### ISSUE THREAD

**Issue by AntonsT** [radical-cybertools/radical.ensemblemd#67]
Terminal output:

2015:04:15 17:43:29 1987   Thread-1     radical.enmd.SingleClusterEnvironment: [ERROR   ] Resource error: Pilot launching failed! (File does not exist: '//home/treikalis/rpd/local/lib/python2.7/site-packages/radical.utils-0.8-py2.7.egg/radical/utils/radical.utils-v0.8-22-g9db58d2-devel.tar.gz' -  (/home/treikalis/rpd/local/lib/python2.7/site-packages/saga_python-0.27-py2.7.egg/saga/adaptors/shell/shell_file.py +1050 (initialize)  :  raise saga.DoesNotExist("File does not exist: '%s' - %s" % (self.url.path, out))))
2015:04:15 17:43:29 1987   Thread-1     radical.enmd.SingleClusterEnvironment: [ERROR   ] Pattern execution FAILED.

**Comment by andre-merzky** [comment]
Thanks Antons!   Would you please let me know how you installed `radical.utils`?  It is not supposed to end up in an egg, but the tar should be at a path like `$VIRTENV/lib/python2.7/site-packages/radical/utils/` and the tarball should be neneath that.  What is the content of `//home/treikalis/rpd/local/lib/python2.7/site-packages/radical.utils-0.8-py2.7.egg/radical/utils/` and `//home/treikalis/rpd/local/lib/python2.7/site-packages/radical/utils/`, respectively?  Thanks!

**Comment by AntonsT** [comment]
> Would you please let me know how you installed radical.utils?

git checkout devel; python  setup.py install

**Comment by AntonsT** [comment]
>Would you please let me know how you installed radical.utils?

Why this makes a difference?

**Comment by andre-merzky** [comment]
Apparently it does.  Please try again with `pip install .`.  In general, please try to always use pip -- different install methods behave very different in python, and specifically don't mix very well...

**Comment by AntonsT** [comment]
CDI usecase did not produce any errors on Stampede with 256 cores and 512 replicas, so I have closed this ticket

**Comment by andre-merzky** [comment]
Thanks for the follow-up!
