### ISSUE TITLE
Missing matrix_calculator.py in Tutorial

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.ensemblemd#74]
I have tried to run Example 4.2.3 Synchronous Replica Exchange Example with 'remote' exchange (generic). In line 141, the function prepare_replica_for_exchange mentions that it requires matrix_calculator.py for the calculator but it is not provided in the tutorial and cannot be found in the documentation.

**Comment by vivek-bala** [comment]
I believe this is the file to be used: https://github.com/radical-cybertools/radical.ensemblemd/blob/master/examples/matrix_calculator.py

**Comment by AntonsT** [comment]
Link to download matrix_calculator.py should be provided in documentation.
