### ISSUE TITLE
replica_exchange.py example fails on stampede, pilot does not become active

### ISSUE THREAD

**Issue by antonst** [radical-cybertools/radical.ensemblemd#79]
Output:
```
2015:08:12 00:40:21 19569  Thread-1     radical.enmd.SingleClusterEnvironment: [INFO    ] Resource stampede.tacc.utexas.edu state has changed to Launching
2015:08:12 00:40:51 19569  Thread-1     radical.enmd.SingleClusterEnvironment: [INFO    ] Resource stampede.tacc.utexas.edu state has changed to PendingActive
2015:08:12 00:43:20 19569  Thread-1     radical.enmd.SingleClusterEnvironment: [INFO    ] Resource stampede.tacc.utexas.edu state has changed to Failed
2015:08:12 00:43:20 19569  Thread-1     radical.enmd.SingleClusterEnvironment: [ERROR   ] Resource error: SAGA job state for ComputePilot pilot.0000 is Failed.
2015:08:12 00:43:20 19569  Thread-1     radical.enmd.SingleClusterEnvironment: [ERROR   ] Pattern execution FAILED.
```

**Comment by AntonsT** [comment]
RP: 0.34 master, ENMD: feature/deallocate (0.2-159-gd181be6)

**Comment by iparask** [comment]
Do you think this is RP or ENMD?

**Comment by AntonsT** [comment]
(agent.err)[https://gist.github.com/AntonsT/b14c4f412a36f929a71e]
(agent.log)[https://gist.github.com/AntonsT/7e7c17a42686b6b9820d]

**Comment by AntonsT** [comment]
Agent bootstrapping seems to be OK (to me), so I am not sure what is the problem

**Comment by vivek-bala** [comment]
Could you post the agent.log ? (agent.log above links to agent.out)

**Comment by AntonsT** [comment]
agent.log is empty

**Comment by vivek-bala** [comment]
Could you run it again with RADICAL_PILOT_VERBOSE=debug. That should populate the agent.log file.

**Comment by AntonsT** [comment]
I can't reproduce this issue Vivek

**Comment by vivek-bala** [comment]
Well, that's good too :) Do we have any idea as to what the fix was (indirectly what the issue was) ?

**Comment by AntonsT** [comment]
>Well, that's good too :) 

No it is not. I don't want this to happen during the tutorial for example. Out of 30 people running the code a couple will get this error.

>Do we have any idea as to what the fix was (indirectly what the issue was) ?

Where was no fix

**Comment by iparask** [comment]
Can you include the whole agent.err file?

**Comment by AntonsT** [comment]
Both agent.err and agent.out are included above

**Comment by vivek-bala** [comment]
Is this issue resolved ? Can you reproduce this ? I wasn't able to reproduce this.

**Comment by vivek-bala** [comment]
according to the testing matrix, this is not encountered anymore.
