### ISSUE TITLE
Suggestions for improving the definitions of concepts and Section 3 (Getting Started)

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.ensemblemd#83]
The definitions for the concepts (application kernel, pattern, execution environment) are currently placed in the Introduction section. It would be more appropriate to move the definitions to Section 3 this information would only be useful after a potential user installs the software. This allows the Introduction section to be a page whose purpose is to convince the reader that EnMD is worth downloading. Moreover, the definitions can be re-worded so as to tie in the example of a generic application defined in Section 3.

The current language used to define concepts should be simplified. They are rigorous and detailed and are suitable for other developers. However, it would be better at this point in the tutorial for a more gradual introduction. Instead of trying to make the definitions as concise as possible, a short list of examples of the methods of the classes can be listed to highlight the function of each concept. In this way the definitions become easier to absorb. Also we can choose particular methods of the class so that the user can get a strong sense of the role each concept; by the time we do introduce the more abstract concept to the reader, he/she will have already inferred it.

**Comment by vivek-bala** [comment]
Follow #100 and #99.
