### ISSUE TITLE
Adding Deallocate to all the scripts and discussing it in the tutorial

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.ensemblemd#85]
Currently all the scripts do no have deallocate(). As such, the resources are not properly released when a user uses Ctrl+C to kill the job. We should include this in all the scripts to properly clean up when cancelling a job. Moreover we should make a point of this in the tutorial and inform the user to best practices.

**Comment by vivek-bala** [comment]
added in faq
