### ISSUE TITLE
Procedure and format for users to raise a ticket

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.ensemblemd#88]
Aside from adding a link to the ticket, we should have a more formal protocol for opening a ticket. Most importantly, we should decide some relevant information that every ticket should include, e.g. version, remote machine, specific pattern, agent.log and error, etc...

Depending on how formally we want to define the basic information to open a ticket, we can mention it in the FAQ, and add a hyperlink that will forward the user to a page to open a ticket. Or, we can detail something in the end of the tutorial on how to open a ticket.

**Comment by andre-merzky** [comment]
That would not only be useful for EnsembleMD, but for all our software projects...

**Comment by vivek-bala** [comment]
added as a question in FAQ.
