### ISSUE TITLE
how output can be verified? 

### ISSUE THREAD

**Issue by antonst** [radical-cybertools/radical.ensemblemd#95]
When I run for example:

python pipeline.py

it shows lots of log messages and then stops at some point. There is no message informing about success/failure of the run and no new files are created. How can I check if run was successful?

**Comment by AntonsT** [comment]
Currently print statements after completion for all examples are different and provide different kinds of information. These should be consistent.

**Comment by vivek-bala** [comment]
RADICAL_ENMD_VERBOSE=REPORT is now added to the docs. This prints ```Pattern execution successfully finished``` on success or ```Execution Interrupted```on failure for all the patterns.
