### ISSUE TITLE
fatal error leads to hang

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.ensemblemd#96]
in the pypeline.py example, an incorrect resource specified leads to a fatal error, as it should.  What should also happen though is that the example then terminates -- which it does not, it just hangs.  Not sure if this is an EnMD or RP problem...

**Comment by andre-merzky** [comment]
The problem seems to be that session.close is not always called.  Please check if that is the case on all examples...

**Comment by vivek-bala** [comment]
fixed in devel. Thanks Andre !
